name: Auto checkin

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login and checkin
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWD: ${{ secrets.PASSWD }}
        run: |
          echo 'start to checkin'
          ./build/src/airport-checkin $EMAIL $PASSWD
